Database Implementation Techniques Programming Task SoSe2015: CoGaDB::DECompressedColumn< T > Class Template Reference
CoGaDB::DECompressedColumn< T > Class Template Reference
This class represents a dictionary compressed column with type T, is the base class for all compressed typed column classes.
#include <deltaEncoding_compressed_column.hpp>
Public Member Functions
DECompressedColumn (const std::string &name, AttributeType db_type)
virtual ~DECompressedColumn ()
virtual bool insert (const boost::any &new_Value)
appends a value new_Value to end of column
virtual bool insert (const T &new_value)
template<typename InputIterator >
bool insert (InputIterator first, InputIterator last)
virtual bool update (TID tid, const boost::any &new_value)
updates the value on position tid with a value new_Value
virtual bool update (PositionListPtr tid, const boost::any &new_value)
updates the values specified by the position list with a value new_Value
virtual bool remove (TID tid)
deletes the value on position tid
virtual bool remove (PositionListPtr tid)
deletes the values defined in the position list
virtual bool clearContent ()
deletes all values stored in the column
virtual const boost::any get (TID tid)
generic function for fetching a value form a column (slow)
virtual void print () const throw ()
prints the content of a column
virtual size_t size () const throw ()
returns the number of values (rows) in a column
virtual unsigned int getSizeinBytes () const throw ()
returns the size in bytes the column consumes in main memory
virtual const ColumnPtr copy () const
virtual copy constructor
virtual bool store (const std::string &path)
store a column on the disc
virtual bool load (const std::string &path)
load column from disc
virtual T & operator[] (const int index)
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
template<>
DECompressedColumn (const std::string &name, AttributeType db_type)
template<>
bool insert (const float &value)
template<>
bool insert (const std::string &value)
template<>
const boost::any get (TID index)
generic function for fetching a value form a column (slow)
template<>
const boost::any get (TID index)
generic function for fetching a value form a column (slow)
template<>
void print () const throw()
prints the content of a column
template<>
void print () const throw()
prints the content of a column
template<>
size_t size () const throw()
returns the number of values (rows) in a column
template<>
bool update (TID id, const boost::any &updatesvalue)
updates the value on position tid with a value new_Value
template<>
bool update (TID id, const boost::any &updatesvalue)
updates the value on position tid with a value new_Value
template<>
bool update (PositionListPtr tids, const boost::any &new_value)
updates the values specified by the position list with a value new_Value
template<>
bool update (PositionListPtr tids, const boost::any &new_value)
updates the values specified by the position list with a value new_Value
template<>
bool remove (TID id)
deletes the value on position tid
template<>
bool remove (TID id)
deletes the value on position tid
template<>
bool clearContent ()
deletes all values stored in the column
template<>
bool clearContent ()
deletes all values stored in the column
template<>
bool store (const std::string &path_)
store a column on the disc
template<>
bool load (const std::string &path_)
load column from disc
template<>
float & operator[] (const int id)
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
template<>
std::string & operator[] (const int id)
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
template<>
unsigned int getSizeinBytes () const throw()
returns the size in bytes the column consumes in main memory
Public Member Functions inherited from CoGaDB::CompressedColumn< T >
CompressedColumn (const std::string &name, AttributeType db_type)
virtual ~CompressedColumn ()
virtual bool isMaterialized () const throw ()
use this method to determine whether the column is materialized or a Lookup Column
virtual bool isCompressed () const throw ()
use this method to determine whether the column is materialized or a Lookup Column
Public Member Functions inherited from CoGaDB::ColumnBaseTyped< T >
ColumnBaseTyped (const std::string &name, AttributeType db_type)
virtual ~ColumnBaseTyped ()
virtual const PositionListPtr sort (SortOrder order)
sorts a column w.r.t. a SortOrder
virtual const PositionListPtr selection (const boost::any &value_for_comparison, const ValueComparator comp)
filters the values of a column according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
virtual const PositionListPtr parallel_selection (const boost::any &value_for_comparison, const ValueComparator comp, unsigned int number_of_threads)
filters the values of a column in parallel according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
virtual const PositionListPairPtr hash_join (ColumnPtr join_column)
joins two columns using the hash join algorithm
virtual const PositionListPairPtr sort_merge_join (ColumnPtr join_column)
joins two columns using the sort merge join algorithm
virtual const PositionListPairPtr nested_loop_join (ColumnPtr join_column)
joins two columns using the nested loop join algorithm
virtual bool add (const boost::any &new_Value)
adds constant to column
virtual bool add (ColumnPtr join_column)
vector addition of two columns
virtual bool minus (const boost::any &new_Value)
substracts constant from column
virtual bool minus (ColumnPtr join_column)
vector substraction of two columns
virtual bool multiply (const boost::any &new_Value)
multiply constant with column
virtual bool multiply (ColumnPtr join_column)
multiply two columns A and B
virtual bool division (const boost::any &new_Value)
devide values in column by a constant
virtual bool division (ColumnPtr join_column)
devide column A with column B
virtual const std::type_info & type () const throw ()
returns type information of internal values
bool operator== (ColumnBaseTyped< T > &column)
template<>
bool add (const boost::any &)
adds constant to column
template<>
bool add (ColumnPtr)
vector addition of two columns
template<>
bool minus (const boost::any &)
substracts constant from column
template<>
bool minus (ColumnPtr)
vector substraction of two columns
template<>
bool multiply (const boost::any &)
multiply constant with column
template<>
bool multiply (ColumnPtr)
multiply two columns A and B
template<>
bool division (const boost::any &)
devide values in column by a constant
template<>
bool division (ColumnPtr)
devide column A with column B
Public Member Functions inherited from CoGaDB::ColumnBase
ColumnBase (const std::string &name, AttributeType db_type)
virtual ~ColumnBase ()
AttributeType getType () const throw ()
returns database type of column (as defined in "SQL" statement)
const std::string getName () const throw ()
returns attribute name of column
Public Attributes
std::vector< T > compressed_vector
std::vector< int > icompressed_vector
int iTotalValue
T TotalValue
T Return_Variable
Additional Inherited Members
Public Types inherited from CoGaDB::ColumnBase
typedef shared_pointer_namespace::shared_ptr< ColumnBase > ColumnPtr
defines a smart pointer to a ColumnBase Object
Protected Attributes inherited from CoGaDB::ColumnBase
std::string name_
attribute name of the column
AttributeType db_type_
database type of the column
Detailed Description
template<class T>
class CoGaDB::DECompressedColumn< T >
This class represents a dictionary compressed column with type T, is the base class for all compressed typed column classes.
Definition at line 17 of file deltaEncoding_compressed_column.hpp.
Constructor & Destructor Documentation
template<class T > CoGaDB::DECompressedColumn< T >::DECompressedColumn (const std::string & name, AttributeType db_type)
Definition at line 67 of file deltaEncoding_compressed_column.hpp.
template<class T > CoGaDB::DECompressedColumn< T >::~DECompressedColumn () virtual
Definition at line 77 of file deltaEncoding_compressed_column.hpp.
template<> CoGaDB::DECompressedColumn< std::string >::DECompressedColumn (const std::string & name, AttributeType db_type)
Definition at line 72 of file deltaEncoding_compressed_column.hpp.
Member Function Documentation
template<class T > bool CoGaDB::DECompressedColumn< T >::clearContent () virtual
deletes all values stored in the column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 577 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::load(), and CoGaDB::DECompressedColumn< T >::update().
template<> bool CoGaDB::DECompressedColumn< float >::clearContent () virtual
deletes all values stored in the column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 584 of file deltaEncoding_compressed_column.hpp.
template<> bool CoGaDB::DECompressedColumn< std::string >::clearContent () virtual
deletes all values stored in the column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 591 of file deltaEncoding_compressed_column.hpp.
template<class T > const ColumnPtr CoGaDB::DECompressedColumn< T >::copy () const virtual
virtual copy constructor
Returns
a ColumnPtr to an exakt copy of the current column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 313 of file deltaEncoding_compressed_column.hpp.
template<class T > const boost::any CoGaDB::DECompressedColumn< T >::get (TID tid) virtual
generic function for fetching a value form a column (slow)
check whether the object is valid (e.g., when a tid is not valid, then the returned object is invalid as well)
Returns
object of type boost::any containing the value on position tid
Implements CoGaDB::CompressedColumn< T >.
Definition at line 219 of file deltaEncoding_compressed_column.hpp.
template<> const boost::any CoGaDB::DECompressedColumn< float >::get (TID tid) virtual
generic function for fetching a value form a column (slow)
check whether the object is valid (e.g., when a tid is not valid, then the returned object is invalid as well)
Returns
object of type boost::any containing the value on position tid
Implements CoGaDB::CompressedColumn< T >.
Definition at line 231 of file deltaEncoding_compressed_column.hpp.
template<> const boost::any CoGaDB::DECompressedColumn< std::string >::get (TID tid) virtual
generic function for fetching a value form a column (slow)
check whether the object is valid (e.g., when a tid is not valid, then the returned object is invalid as well)
Returns
object of type boost::any containing the value on position tid
Implements CoGaDB::CompressedColumn< T >.
Definition at line 245 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::stringadd().
template<class T > unsigned int CoGaDB::DECompressedColumn< T >::getSizeinBytes () const throw () virtual
returns the size in bytes the column consumes in main memory
Implements CoGaDB::CompressedColumn< T >.
Definition at line 713 of file deltaEncoding_compressed_column.hpp.
template<> unsigned int CoGaDB::DECompressedColumn< float >::getSizeinBytes () const throw () virtual
returns the size in bytes the column consumes in main memory
Implements CoGaDB::CompressedColumn< T >.
Definition at line 718 of file deltaEncoding_compressed_column.hpp.
template<class T > bool CoGaDB::DECompressedColumn< T >::insert (const boost::any & new_Value) virtual
appends a value new_Value to end of column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 82 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::insert(), and CoGaDB::DECompressedColumn< T >::update().
template<class T > bool CoGaDB::DECompressedColumn< T >::insert (const T & new_value) virtual
Implements CoGaDB::CompressedColumn< T >.
Definition at line 94 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::TotalValue.
template<typename T > template<typename InputIterator > bool CoGaDB::DECompressedColumn< T >::insert (InputIterator first, InputIterator last)
Definition at line 204 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::insert().
template<> bool CoGaDB::DECompressedColumn< float >::insert (const float & value)
Definition at line 116 of file deltaEncoding_compressed_column.hpp.
template<> bool CoGaDB::DECompressedColumn< std::string >::insert (const std::string & value)
Definition at line 181 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::stringadd(), and CoGaDB::stringsub().
template<class T > bool CoGaDB::DECompressedColumn< T >::load (const std::string & path) virtual
load column from disc
calling load on a column that is not empty yields undefined behaviour
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 633 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::clearContent(), CoGaDB::DECompressedColumn< T >::compressed_vector, CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::TotalValue.
template<> bool CoGaDB::DECompressedColumn< float >::load (const std::string & path) virtual
load column from disc
calling load on a column that is not empty yields undefined behaviour
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 650 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::clearContent(), CoGaDB::DECompressedColumn< T >::icompressed_vector, CoGaDB::DECompressedColumn< T >::iTotalValue, and CoGaDB::ColumnBase::name_.
template<class T > T & CoGaDB::DECompressedColumn< T >::operator[] (const int index) virtual
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
Note that this method is pure virtual, so it has to be defined in a derived class.
Returns
a reference to the value at position index
Implements CoGaDB::CompressedColumn< T >.
Definition at line 667 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::Return_Variable.
template<> float & CoGaDB::DECompressedColumn< float >::operator[] (const int index) virtual
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
Note that this method is pure virtual, so it has to be defined in a derived class.
Returns
a reference to the value at position index
Implements CoGaDB::CompressedColumn< T >.
Definition at line 683 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::Return_Variable.
template<> std::string & CoGaDB::DECompressedColumn< std::string >::operator[] (const int index) virtual
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
Note that this method is pure virtual, so it has to be defined in a derived class.
Returns
a reference to the value at position index
Implements CoGaDB::CompressedColumn< T >.
Definition at line 699 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::Return_Variable, and CoGaDB::stringadd().
template<class T > void CoGaDB::DECompressedColumn< T >::print () const throw () virtual
prints the content of a column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 260 of file deltaEncoding_compressed_column.hpp.
template<> void CoGaDB::DECompressedColumn< float >::print () const throw () virtual
prints the content of a column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 273 of file deltaEncoding_compressed_column.hpp.
template<> void CoGaDB::DECompressedColumn< std::string >::print () const throw () virtual
prints the content of a column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 286 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::stringadd().
template<class T > bool CoGaDB::DECompressedColumn< T >::remove (TID tid) virtual
deletes the value on position tid
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 533 of file deltaEncoding_compressed_column.hpp.
template<class T > bool CoGaDB::DECompressedColumn< T >::remove (PositionListPtr tid) virtual
deletes the values defined in the position list
assumes tid list is sorted ascending
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 560 of file deltaEncoding_compressed_column.hpp.
template<> bool CoGaDB::DECompressedColumn< float >::remove (TID tid) virtual
deletes the value on position tid
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 542 of file deltaEncoding_compressed_column.hpp.
template<> bool CoGaDB::DECompressedColumn< std::string >::remove (TID tid) virtual
deletes the value on position tid
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 551 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::stringadd().
template<class T > size_t CoGaDB::DECompressedColumn< T >::size () const throw () virtual
returns the number of values (rows) in a column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 298 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::update().
template<> size_t CoGaDB::DECompressedColumn< float >::size () const throw () virtual
returns the number of values (rows) in a column
Implements CoGaDB::CompressedColumn< T >.
Definition at line 305 of file deltaEncoding_compressed_column.hpp.
template<class T > bool CoGaDB::DECompressedColumn< T >::store (const std::string & path) virtual
store a column on the disc
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 599 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::compressed_vector, CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::TotalValue.
template<> bool CoGaDB::DECompressedColumn< float >::store (const std::string & path) virtual
store a column on the disc
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 616 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::icompressed_vector, CoGaDB::DECompressedColumn< T >::iTotalValue, and CoGaDB::ColumnBase::name_.
template<class T > bool CoGaDB::DECompressedColumn< T >::update (TID tid, const boost::any & new_Value) virtual
updates the value on position tid with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 319 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::size().
template<class T > bool CoGaDB::DECompressedColumn< T >::update (PositionListPtr tids, const boost::any & new_value) virtual
updates the values specified by the position list with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 419 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::clearContent(), CoGaDB::DECompressedColumn< T >::compressed_vector, CoGaDB::DECompressedColumn< T >::insert(), CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::size().
template<> bool CoGaDB::DECompressedColumn< float >::update (TID tid, const boost::any & new_Value) virtual
updates the value on position tid with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 352 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::size().
template<> bool CoGaDB::DECompressedColumn< std::string >::update (TID tid, const boost::any & new_Value) virtual
updates the value on position tid with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 386 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::ColumnBase::name_, CoGaDB::DECompressedColumn< T >::size(), CoGaDB::stringadd(), and CoGaDB::stringsub().
template<> bool CoGaDB::DECompressedColumn< float >::update (PositionListPtr tids, const boost::any & new_value) virtual
updates the values specified by the position list with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 456 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::icompressed_vector, CoGaDB::DECompressedColumn< T >::insert(), CoGaDB::ColumnBase::name_, and CoGaDB::DECompressedColumn< T >::size().
template<> bool CoGaDB::DECompressedColumn< std::string >::update (PositionListPtr tids, const boost::any & new_value) virtual
updates the values specified by the position list with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::CompressedColumn< T >.
Definition at line 494 of file deltaEncoding_compressed_column.hpp.
References CoGaDB::DECompressedColumn< T >::compressed_vector, CoGaDB::DECompressedColumn< T >::insert(), CoGaDB::ColumnBase::name_, CoGaDB::DECompressedColumn< T >::size(), and CoGaDB::stringadd().
Member Data Documentation
template<class T > std::vector<T> CoGaDB::DECompressedColumn< T >::compressed_vector
Definition at line 21 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::load(), CoGaDB::DECompressedColumn< T >::store(), and CoGaDB::DECompressedColumn< T >::update().
template<class T > std::vector<int> CoGaDB::DECompressedColumn< T >::icompressed_vector
Definition at line 22 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::load(), CoGaDB::DECompressedColumn< T >::store(), and CoGaDB::DECompressedColumn< T >::update().
template<class T > int CoGaDB::DECompressedColumn< T >::iTotalValue
Definition at line 23 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::load(), and CoGaDB::DECompressedColumn< T >::store().
template<class T > T CoGaDB::DECompressedColumn< T >::Return_Variable
Definition at line 25 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::operator[]().
template<class T > T CoGaDB::DECompressedColumn< T >::TotalValue
Definition at line 24 of file deltaEncoding_compressed_column.hpp.
Referenced by CoGaDB::DECompressedColumn< T >::insert(), CoGaDB::DECompressedColumn< T >::load(), and CoGaDB::DECompressedColumn< T >::store().
The documentation for this class was generated from the following file:
deltaEncoding_compressed_column.hpp